I'm sorry, but an uncaught exception occurred.

While running game code:
KeyError: u"'The Show Must Be Go"

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/hedley/script.rpyc", line 1420, in script
  File "/home/hedley/Documents/renpy/renpy/ast.py", line 604, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "/home/hedley/Documents/renpy/renpy/exports.py", line 1122, in say
    who(what, interact=interact)
  File "/home/hedley/Documents/renpy/renpy/character.py", line 832, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=translate))
  File "/home/hedley/Documents/renpy/renpy/character.py", line 814, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/home/hedley/Documents/renpy/renpy/substitutions.py", line 229, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u"'The Show Must Be Go"

Linux-3.19.0-32-generic-x86_64-with-debian-jessie-sid
Ren'Py 6.99.10.1227
Programar con Python 0.0
